name = "Freaworld"
author = "Miohouse"
version = "0.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "175bdd9aa771e94734544f5988ceb7cdd87aba189465b8fa29c82107c28f9398"

[versions]
minecraft = "1.18.2"
quilt = "0.18.1-beta.21"
