name = "Freaworld"
author = "Miohouse"
version = "0.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60bbf50dbfa6818d7f22fb77551bb60fb5d02052188669e6ee4e785d846f3ecf"

[versions]
minecraft = "1.18.2"
quilt = "0.18.1-beta.21"
